#!/bin/bash
set -o errexit -o nounset -o pipefail

ec=0
[ -z "${LOGIN-}" -o -z "${PASSWORD-}" ] && echo "Please provide a LOGIN and PASSWORD environment variable" && ec=1
[ -z "${PROXY_PASS-}" ] && echo "Please provide the PROXY_PASS environment variable" && ec=1
[ $ec -ne 0 ] && exit 1

: "${SERVER_NAME:=_}" "${LOCATION:=/}"
export SERVER_NAME LOCATION
echo "Writing config"
envsubst < /etc/nginx/conf.d/auth-proxy.template > /etc/nginx/conf.d/auth-proxy.conf
echo "  location $LOCATION {
    auth_basic \"$SERVER_NAME\";
    auth_basic_user_file /etc/nginx/auth/htpasswd;
    rewrite ^${LOCATION%/}/(.*) /\$1 break;
    proxy_redirect off;
    proxy_set_header Host \$host;
    proxy_set_header X-Real-IP \$remote_addr;
    proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto \$scheme;
    proxy_pass $PROXY_PASS;
  }" >> /etc/nginx/conf.d/auth-proxy.conf
echo -e "Writing user file:\n\t- $LOGIN"
echo "$LOGIN:$PASSWORD" > /etc/nginx/auth/htpasswd
for i in {0..100}; do
  userenv="LOGIN$i"
  passwdenv="PASSWORD$i"
  if [ -n "${!userenv-}" -a -n "${!passwdenv-}" ]; then
    echo -e "\t- ${!userenv}"
    echo "${!userenv}:${!passwdenv}" >> /etc/nginx/auth/htpasswd
  fi

  location="LOCATION$i"
  proxy_pass="PROXY_PASS$i"
  if [ -n "${!location-}" -a -n "${!proxy_pass-}" ]; then
    echo "  location ${!location} {
    auth_basic \"$SERVER_NAME\";
    auth_basic_user_file /etc/nginx/auth/htpasswd;
    rewrite ^${!location%/}/(.*) /\$1 break;
    proxy_redirect off;
    proxy_set_header Host \$host;
    proxy_set_header X-Real-IP \$remote_addr;
    proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto \$scheme;
    proxy_pass ${!proxy_pass};
  }" >> /etc/nginx/conf.d/auth-proxy.conf
  fi
done
echo "}" >> /etc/nginx/conf.d/auth-proxy.conf
echo "Starting DC/OS auth proxy"
exec /usr/sbin/nginx -g 'daemon off;'
