#!/bin/bash
set -o errexit -o nounset -o pipefail

ec=0
[ -z "${LOGIN-}" -o -z "${PASSWORD-}" ] && echo "Please provide a LOGIN and PASSWORD environment variable" && ec=1
[ -z "${PROXY_PASS-}" ] && echo "Please provide the PROXY_PASS environment variable" && ec=1
[ $ec -ne 0 ] && exit 1

export SERVER_NAME="${SERVER_NAME:-_}"
export LOCATION="${LOCATION:-/}"
echo "Writing config"
envsubst < /etc/nginx/conf.d/auth-proxy.template > /etc/nginx/conf.d/auth-proxy.conf
echo -e "Writing user file:\n\t- $LOGIN"
echo "$LOGIN:$PASSWORD" > /etc/nginx/auth/htpasswd
for i in {0..100}; do
  userenv="LOGIN$i"
  passwdenv="PASSWORD$i"
  if [ -n "${!userenv-}" -a -n "${!passwdenv-}" ]; then
    echo -e "\t- ${!userenv}"
    echo "${!userenv}:${!passwdenv}" >> /etc/nginx/auth/htpasswd
  fi
done
echo "Starting DC/OS auth proxy"
exec /usr/sbin/nginx -g 'daemon off;'
